.depends/*.paths for checking dependency
based on some files/dirs exist or not, relative to the $DEPENDSDIR.

diff --git a/check-depends b/check-depends
--- a/check-depends
+++ b/check-depends
@@ -8,30 +8,55 @@ DEPENDSDIR=${1:-$PWD/.depends}
 [ -d "$DEPENDSDIR" ] || exit 0
 export DEPENDSDIR
 
-for cmds in "$DEPENDSDIR"/*.commands; do
-    package=${cmds%.commands}
-    package=${package#$DEPENDSDIR/}
-    sed <"$cmds" 's/#.*$//; /^[ 	]*$/d' |
-    while read -r cmd; do
-        # check if command is available
-        if ! type "$cmd" &>/dev/null; then
-            # run shell script if exists
-            sh="$DEPENDSDIR"/"$package".sh
-            if [ -x "$sh" ]; then
-                echo "### BuildKit: preparing dependency $package"
-                "$sh"
-                break
-            fi
-            # TODO brew/apt-get/yum install based on uname
-            echo "### BuildKit: $cmd: command not found for dependency $package" >&2
-            # show instruction if exists
-            desc="$DEPENDSDIR"/"$package".txt
-            if [ -r "$desc" ]; then
-                cat "$desc" >&2
-                break
-            fi
-            false
+without-comments() { sed 's/#.*$//; /^[ 	]*$/d' "$@"; }
+
+# enumerate dependencies from the specifications
+(
+    cd "$DEPENDSDIR"
+    for f in *.{commands,paths}; do echo "${f%.*}"; done
+) | sort -u |
+while read -r dep; do
+    # define path for dependency specifications
+    dep() { echo "$DEPENDSDIR/$dep.$1"; }
+    # define how to prepare the dependency when not found
+    prepare-dependency() {
+        # run shell script if exists
+        sh=$(dep sh)
+        if [ -x "$sh" ]; then
+            echo "### BuildKit: preparing dependency $dep"
+            "$sh"
+            return 0
         fi
-    done
-    echo "### BuildKit: found dependency $package"
+        # TODO brew/apt-get/yum install based on uname
+        echo "### BuildKit: $cmd: command not found for dependency $dep" >&2
+        # show instruction if exists
+        desc=$(dep txt)
+        if [ -r "$desc" ]; then
+            cat "$desc" >&2
+            return 0
+        fi
+        false
+    }
+
+    # check if all required commands are available
+    cmds=$(dep commands)
+    if [ -r "$cmds" ]; then
+        without-comments "$cmds" |
+        while read -r cmd; do
+            type "$cmd" &>/dev/null ||
+                prepare-dependency
+        done
+    fi
+
+    # check if all required paths exists
+    paths=$(dep paths)
+    if [ -r "$paths" ]; then
+        without-comments "$paths" |
+        while read -r path; do
+            (cd "$DEPENDSDIR" && [ -e "$path" ]) ||
+                prepare-dependency
+        done
+    fi
+
+    echo "### BuildKit: found dependency $dep"
 done
